/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fibonaccindk_FibonacciNDK */

#ifndef _Included_com_fibonaccindk_FibonacciNDK
#define _Included_com_fibonaccindk_FibonacciNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fibonaccindk_FibonacciNDK
 * Method:    fibonacciNativoR
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_fibonaccindk_FibonacciNDK_fibonacciNativoR
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fibonaccindk_FibonacciNDK
 * Method:    fibonacciNativoI
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_fibonaccindk_FibonacciNDK_fibonacciNativoI
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
